import { strict as assert } from 'node:assert';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { type ModelMessage, streamText } from 'ai';
import 'dotenv/config';

type FetchObservation = {
  requestBody: string | undefined;
  responseBody: Promise<string>;
  status: number;
  url: string;
};

function sanitizeFixture(raw: string): string {
  return raw
    .split('\n')
    .map(line => {
      if (!line.startsWith('data: ')) {
        return line;
      }

      const value = JSON.parse(line.slice('data: '.length));

      for (const candidate of value.candidates ?? []) {
        for (const part of candidate.content?.parts ?? []) {
          if (part.inlineData?.data != null) {
            part.inlineData.data = 'AA==';
          }
          if (part.thoughtSignature != null) {
            part.thoughtSignature = 'live-image-thought-signature';
          }
        }
      }

      return `data: ${JSON.stringify(value)}`;
    })
    .join('\n');
}

function hasImageThoughtSignature(raw: string): boolean {
  return raw.split('\n').some(line => {
    if (!line.startsWith('data: ')) {
      return false;
    }

    const value = JSON.parse(line.slice('data: '.length));
    return (value.candidates ?? []).some((candidate: any) =>
      (candidate.content?.parts ?? []).some(
        (part: any) =>
          part.inlineData != null &&
          typeof part.thoughtSignature === 'string' &&
          part.thoughtSignature.length > 0,
      ),
    );
  });
}

function historyHasImageThoughtSignature(messages: ModelMessage[]): boolean {
  return messages.some(
    message =>
      message.role === 'assistant' &&
      Array.isArray(message.content) &&
      message.content.some(
        part =>
          part.type === 'file' &&
          typeof part.providerOptions?.google?.thoughtSignature === 'string',
      ),
  );
}

async function runRefinement({
  messages,
  model,
}: {
  messages: ModelMessage[];
  model: ReturnType<ReturnType<typeof createGoogleGenerativeAI>>;
}) {
  const result = streamText({
    model,
    messages,
    providerOptions: {
      google: { responseModalities: ['TEXT', 'IMAGE'] },
    },
  });

  let error: unknown;
  let imageCount = 0;
  try {
    for await (const part of result.fullStream) {
      if (part.type === 'file') {
        imageCount++;
      } else if (part.type === 'error') {
        error = part.error;
      }
    }
  } catch (caughtError) {
    error = caughtError;
  }

  return { error, imageCount };
}

async function main() {
  const observations: FetchObservation[] = [];
  const recordingFetch: typeof fetch = async (input, init) => {
    const response = await fetch(input, init);
    observations.push({
      requestBody:
        typeof init?.body === 'string' ? init.body : init?.body?.toString(),
      responseBody: response.clone().text(),
      status: response.status,
      url: String(input),
    });
    return response;
  };

  const google = createGoogleGenerativeAI({ fetch: recordingFetch });
  const model = google('gemini-3-pro-image-preview');
  const firstUserMessage: ModelMessage = {
    role: 'user',
    content: 'Create an image of the moon.',
  };

  const firstResult = streamText({
    model,
    messages: [firstUserMessage],
    providerOptions: {
      google: { responseModalities: ['TEXT', 'IMAGE'] },
    },
  });
  const firstResponse = await firstResult.response;
  const firstRawResponse = await observations[0].responseBody;

  const fixturePath = resolve(
    process.cwd(),
    '../../packages/google/src/__fixtures__/issue-10660-image-thought-signature.chunks.txt',
  );
  await mkdir(resolve(fixturePath, '..'), { recursive: true });
  await writeFile(fixturePath, sanitizeFixture(firstRawResponse));

  const firstImageCount = firstResponse.messages
    .filter(message => message.role === 'assistant')
    .flatMap(message => (Array.isArray(message.content) ? message.content : []))
    .filter(part => part.type === 'file').length;
  const rawHasSignature = hasImageThoughtSignature(firstRawResponse);
  const historyHasSignature = historyHasImageThoughtSignature(
    firstResponse.messages,
  );

  assert.ok(
    firstImageCount > 0,
    'The first streaming request returned no image.',
  );
  assert.ok(
    rawHasSignature,
    'The live provider response did not sign an image part.',
  );

  const messages: ModelMessage[] = [
    firstUserMessage,
    ...firstResponse.messages,
    { role: 'user', content: 'Nice, but now make it cheese.' },
  ];
  const directRefinement = await runRefinement({ messages, model });

  // The current model returns JPEG, while this old provider release only accepts
  // PNG assistant images. Relabel the already generated bytes for one narrowing
  // request so the request reaches Google and tests the missing signature.
  const narrowedMessages = structuredClone(messages);
  for (const message of narrowedMessages) {
    if (message.role !== 'assistant' || !Array.isArray(message.content)) {
      continue;
    }
    for (const part of message.content) {
      if (part.type === 'file') {
        part.mediaType = 'image/png';
      }
    }
  }
  const narrowedRefinement = await runRefinement({
    messages: narrowedMessages,
    model,
  });

  console.log(
    JSON.stringify(
      {
        firstImageCount,
        rawHasSignature,
        historyHasSignature,
        directRefinement: {
          imageCount: directRefinement.imageCount,
          error:
            directRefinement.error instanceof Error
              ? {
                  message: directRefinement.error.message,
                  name: directRefinement.error.name,
                }
              : directRefinement.error,
        },
        narrowedRefinement: {
          imageCount: narrowedRefinement.imageCount,
          error:
            narrowedRefinement.error instanceof Error
              ? {
                  message: narrowedRefinement.error.message,
                  name: narrowedRefinement.error.name,
                }
              : narrowedRefinement.error,
        },
        requests: await Promise.all(
          observations.map(async observation => ({
            requestHasThoughtSignature:
              observation.requestBody?.includes('thoughtSignature') ?? false,
            responseStatus: observation.status,
            responseText: (await observation.responseBody).slice(0, 500),
            url: observation.url,
          })),
        ),
        fixturePath,
      },
      null,
      2,
    ),
  );

  assert.equal(
    directRefinement.error,
    undefined,
    'The follow-up streaming image refinement failed.',
  );
  assert.ok(
    directRefinement.imageCount > 0,
    'The follow-up streaming request returned no refined image.',
  );
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
